from pathlib import Path
from html import escape as esc
from content import chapters, DOC, REPO
from visual_content import STORIES, storyboard, pipeline
ROOT=Path(__file__).parent
SITE=ROOT/'site'
BASE='https://sweetweeds.github.io/xiangshan-book/'
def shell(title,desc,body,path='index.html'):
 p='../' if path.startswith('chapters/') else './'
 return f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} · XiangShan Book</title><meta name="description" content="{esc(desc)}"><meta name="theme-color" content="#173e33"><link rel="canonical" href="{BASE+path}"><meta property="og:title" content="{esc(title)} · XiangShan Book"><meta property="og:description" content="{esc(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="{BASE+path}"><link rel="icon" href="{p}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{p}assets/style.css"><link rel="stylesheet" href="{p}assets/visuals.css"><script src="{p}assets/app.js" defer></script><script src="{p}assets/visuals.js" defer></script></head><body><a class="skip" href="#main">본문으로 이동</a><header><div class="nav"><a class="brand" href="{p}index.html"><span class="mark">山</span> XiangShan<span class="brand-light"> / Book</span></a><nav aria-label="주 메뉴"><a href="{p}index.html#chapters">목차</a><a href="{p}index.html#labs">실험실</a><a href="{p}index.html#resources">자료</a><button class="theme" aria-label="다크 모드 전환" title="테마 바꾸기">◐</button></nav></div></header>{body}<footer><div><a class="brand" href="{p}index.html">山 XiangShan Book</a><p>열린 설계를, 이해할 수 있는 지식으로.</p></div><div><p>독립적으로 제작한 비공식 한국어 학습 자료입니다.</p><p>설계 참고: <a href="{DOC}">The XiangShan Team · 공식 문서</a> (<a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>). 한국어 설명·교육 예제로 재구성했습니다.<br>학습 경험 참고: <a href="https://computerbook.euiyun.com/">ComputerBook</a> · 디자인과 코드는 새로 작성했습니다.</p><a href="https://github.com/SweetWeeds/xiangshan-book">사이트 소스 ↗</a></div></footer></body></html>'''
def card(i,c):
 return f'''<a class="chapter-card" data-search="{esc(c['title']+' '+c['desc']+' '+c['tag'])}" data-chapter="{c['slug']}" href="chapters/{c['slug']}.html"><span class="chapter-num">{i+1:02}</span><div><small>{c['tag']} · 약 {c['time']}분</small><h3>{c['title']}</h3><p>{c['desc']}</p></div><span class="card-arrow" aria-hidden="true">↗</span></a>'''
hero='''<section class="hero"><div class="hero-copy"><p class="eyebrow"><span class="dot"></span> OPEN HARDWARE, OPEN KNOWLEDGE</p><h1>명령어 하나에서<br><em>고성능 코어</em>까지.</h1><p class="lead">XiangShan으로 배우는 프로세서 설계.<br>읽고, 직접 움직이고, 소스 코드로 연결하는<br>한국어 인터랙티브 교과서입니다.</p><div class="actions"><a class="button primary" href="chapters/start.html">첫 장 시작하기 <span>↗</span></a><a class="text-link" href="#chapters">전체 목차 보기 ↓</a></div><p class="hero-note">RISC-V 기초부터 · 무료 · 설치 없이 브라우저에서</p></div><div class="hero-art" aria-label="XiangShan 코어를 상징하는 칩 일러스트"><span class="art-label">FIELD GUIDE / 01</span><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="chip"><div class="chip-inner"><span class="chip-symbol">山</span><strong>XiangShan</strong><small>RISC-V · OPEN CORE</small></div></div><span class="art-coordinate">香山 / INSIDE THE PROCESSOR</span><span class="art-corner">↗</span></div></section>'''
body='<main id="main" class="home">'+hero+'''<div class="facts"><div><b>10<span>개 장</span></b><p>개념에서 소스 읽기까지</p></div><div><b>10<span>개 시각화</span></b><p>4개 실험과 6개 단계별 그림</p></div><div><b>RISC-V</b><p>공개 ISA, 열린 프로세서 설계</p></div><div><b>V2<span>문서 기준</span></b><p>Kunminghu 계열 개념 안내</p></div></div>
<section class="paths-section"><div class="section-heading"><div><p class="eyebrow">CHOOSE YOUR PATH</p><h2>어디서부터 읽어 볼까요?</h2></div><p>궁금한 곳부터 시작해도 좋습니다.</p></div><div class="paths"><a href="chapters/start.html"><span>01 / 처음 만나는 분께</span><h3>코어의 큰 그림부터</h3><p>ISA와 구현의 차이를 이해하고<br>명령어의 여정을 따라가 보세요.</p><b>1 → 2 → 3장 <i>↗</i></b></a><a href="chapters/prediction.html"><span>02 / 직접 만져 보고 싶다면</span><h3>실험으로 감 잡기</h3><p>예측 상태를 바꾸고, 실행 순서를 보고,<br>캐시 미스를 만들어 보세요.</p><b>4 → 6 → 8장 <i>↗</i></b></a><a href="chapters/verification.html"><span>03 / 설계 코드를 읽는 분께</span><h3>이해에서 검증으로</h3><p>개발 도구의 역할을 구분하고<br>버전과 Config를 확인하는 습관까지.</p><b>9 → 10장 <i>↗</i></b></a></div></section>
<section id="chapters"><div class="section-heading"><div><p class="eyebrow">THE CHAPTERS</p><h2>차근차근, 코어 안으로.</h2></div><div class="search-wrap"><label for="search">목차 검색</label><input id="search" type="search" placeholder="분기 예측, 캐시, 검증…"></div></div><div class="progress-line"><span id="progress-label">읽음 표시 0 / 10</span><progress id="progress" max="10" value="0" aria-label="읽은 장 수"></progress><button id="clear-progress" class="text-button">기록 초기화</button></div><p class="search-result" id="search-result" role="status"></p><div class="chapter-grid">'''+''.join(card(i,c) for i,c in enumerate(chapters))+'''</div><p id="no-results" hidden>일치하는 장이 없습니다. 다른 키워드로 검색해 보세요.</p></section>
<section id="labs" class="lab-feature"><div><p class="eyebrow">LESS READING, MORE UNDERSTANDING</p><h2>“만약에”를<br>직접 눌러 보세요.</h2><p>분기 예측이 빗나가면? 캐시가 충돌하면?<br>작은 모형에서 변화를 관찰하면<br>복잡한 설계를 읽을 단서가 생깁니다.</p><span class="model-note">모든 실험은 원리 학습용 단순화 모형입니다.</span></div><div class="lab-links"><a href="chapters/pipeline.html#experiment"><span>01</span><div><h3>파이프라인 애니메이션</h3><p>명령어가 겹쳐 움직이는 시간표</p></div><b>→</b></a><a href="chapters/prediction.html#experiment"><span>02</span><div><h3>분기 예측 실험</h3><p>2비트 카운터의 기억과 학습</p></div><b>→</b></a><a href="chapters/ooo.html#experiment"><span>03</span><div><h3>비순차 실행 실험</h3><p>완료는 자유롭게, 커밋은 순서대로</p></div><b>→</b></a><a href="chapters/cache.html#experiment"><span>04</span><div><h3>캐시 접근 실험</h3><p>주소를 바꾸며 적중과 충돌 관찰</p></div><b>→</b></a></div></section>
<section id="resources"><div class="section-heading"><div><p class="eyebrow">GO TO THE SOURCE</p><h2>다음 페이지는, 실제 설계.</h2></div><p>더 깊은 내용은 공식 자료로 이어집니다.</p></div><div class="resources"><a href="https://github.com/OpenXiangShan/XiangShan"><small>GITHUB</small><h3>XiangShan 소스 코드 ↗</h3><p>브랜치, 구성, 구현을 직접 확인하세요.</p></a><a href="https://docs.xiangshan.cc/projects/design/en/kunminghu-v2/"><small>DESIGN DOCUMENT</small><h3>Kunminghu V2 설계 문서 ↗</h3><p>각 모듈의 기능과 인터페이스를 읽어 보세요.</p></a><a href="https://docs.xiangshan.cc/projects/user-guide/en/kunminghu-v2/"><small>USER GUIDE</small><h3>공식 사용자 가이드 ↗</h3><p>구성과 소프트웨어 인터페이스를 살펴보세요.</p></a></div></section></main>'''
(SITE/'index.html').write_text(shell('열린 설계로 배우는 고성능 RISC-V','XiangShan 한국어 인터랙티브 교과서. 10개 장과 4개 실험으로 분기 예측, 비순차 실행, 캐시와 검증을 배웁니다.',body))
for i,c in enumerate(chapters):
 sidebar='<aside class="sidebar"><p class="eyebrow">READ THE CORE</p><a href="../index.html#chapters">← 전체 목차</a><nav aria-label="장 목록">'+''.join(f'<a {"aria-current=page" if k==i else ""} href="{x["slug"]}.html"><span>{k+1:02}</span>{x["title"]}</a>' for k,x in enumerate(chapters))+'</nav></aside>'
 article=f'<main id="main" class="reading">{sidebar}<article data-slug="{c["slug"]}"><div class="chapter-heading"><p class="eyebrow">CHAPTER {i+1:02} / {c["tag"]}</p><h1>{c["title"]}</h1><p class="lead">{c["desc"]}</p><p class="meta">약 {c["time"]}분 · Kunminghu V2 문서 기반 · 개념 학습</p></div>'
 for j,(h,p) in enumerate(c['sections']):
  article+=f'<section><h2><span class="section-index">0{j+1}</span>{h}</h2><p>{p}</p></section>'
  if j == 0 and c['slug'] in STORIES: article+=storyboard(c['slug'])
  if j == 0 and c['slug'] == 'pipeline': article+=pipeline()
 if c.get('diagram'): article+='<figure class="diagram"><img src="../assets/core.svg" alt="BPU에서 Fetch, Decode와 Rename, Issue로 진행하며 실행 유닛과 Load/Store를 거쳐 ROB에서 순서대로 커밋하는 개념도. 메모리는 Load/Store와 연결되고, 잘못된 예측은 BPU로 리다이렉트됩니다."><figcaption>기능 관계의 개념도 · 물리 배치와 실제 파이프라인 단계 수를 나타내지 않습니다.</figcaption></figure>'
 if c.get('sim'): article+=f'<section id="experiment" class="experiment" data-sim="{c["sim"]}"><p class="eyebrow">INTERACTIVE LAB</p><h2>직접 실험하기</h2><p class="model-note">원리 학습용 모형 · 실제 XiangShan의 구성, 타이밍, 성능을 재현하지 않습니다.</p><div id="sim-root"></div><noscript>실험에는 JavaScript가 필요합니다. 본문과 퀴즈 설명은 그대로 읽을 수 있습니다.</noscript></section>'
 article+=f'<div class="takeaway"><small>기억할 한 가지</small><p>{c["takeaway"]}</p></div><section class="quiz" data-answer="{c["answer"]}" data-why="{esc(c["why"])}"><p class="eyebrow">CHECK YOUR UNDERSTANDING</p><h2>확인해 볼까요?</h2><p>{c["q"]}</p><div class="quiz-options">'+''.join(f'<button data-option="{k}"><span>{k+1}</span>{o}</button>' for k,o in enumerate(c['options']))+f'</div><p class="quiz-feedback" role="status"></p><details><summary>정답과 해설 보기</summary><p>정답 {c["answer"]+1}. {c["why"]}</p></details></section>'
 article+='<section class="sources"><h2>더 깊이 읽기</h2>'+''.join(f'<a href="{url}">{name} ↗</a>' for name,url in c['sources'])+'</section><div class="finish"><button class="button primary" id="mark-read" aria-pressed="false">이 장을 읽었어요 ✓</button><p id="save-status" role="status">읽음 표시는 이 브라우저에만 저장됩니다.</p></div><nav class="chapter-pager" aria-label="이전 다음 장">'
 article+=f'<a href="{chapters[i-1]["slug"]}.html">← {chapters[i-1]["title"]}</a>' if i else '<a href="../index.html">← 처음으로</a>'
 article+=f'<a href="{chapters[i+1]["slug"]}.html">{chapters[i+1]["title"]} →</a>' if i<9 else '<a href="../index.html#chapters">목차로 돌아가기 →</a>'
 article+='</nav></article></main>'
 (SITE/'chapters'/f'{c["slug"]}.html').write_text(shell(c['title'],c['desc'],article,f'chapters/{c["slug"]}.html'))
(SITE/'404.html').write_text(shell('페이지를 찾을 수 없습니다','XiangShan Book 목차로 돌아가기','<main id="main" class="home error-page"><p class="eyebrow">404</p><h1>이 경로에는 페이지가 없어요.</h1><p>목차에서 읽고 싶은 장을 다시 찾아보세요.</p><a class="button primary" href="/xiangshan-book/">목차로 돌아가기 →</a></main>','404.html').replace('href="./assets/','href="/xiangshan-book/assets/').replace('src="./assets/','src="/xiangshan-book/assets/').replace('href="./index.html','href="/xiangshan-book/index.html'))
(SITE/'.nojekyll').touch()
(SITE/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{BASE+p}</loc></url>' for p in ['index.html']+[f'chapters/{c["slug"]}.html' for c in chapters])+'</urlset>')
print('Built 10 chapters, homepage, 404 and sitemap.')
